#!/bin/bash
#12.06.2017 01:32:45
#
#----------------------------------------------------------------------
#  HB_DashCam_Converter_Beta-Tester.sh
#  
#  Copyright 2017 Jason Procknow <jprocknow@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  


#---------------------------------------------------------------------
#
#           Notes about sourced code that started this script
#
#initiale source of this script was sourced from the below link
#source: https://surlyjake.com/blog/2010/08/10/script-to-run-handbrake-recursively-through-a-folder-tree/
#the current script currently has only a couple lines of code at most of 
#original, un-edited code.
#---------------------------------------------------------------------

#----------------------------------------------------------------------
#   This script is the beta version of the DashCam convertion script that
#   uses HandbreakCLI to re-encode the 3 minute AVI files generated by my
#   car's dashcam. When the AVI video file is re-encoded to a mp4 codec
#   the size of the file is on average reduced from around 400 MB to 
#   only 40 MB.  The is a file size reduction of about 10 percent. I do
#   this to save hard drive space.  The re-encoded 40 MB .mp4 version of the 
#   video file looks just as good in video quallity as the 400 MB AVI
#   version of the video file.  The re-encoding of these Dashcam video 
#   files reduced the amount of hard drive used by 90%.  This is why I
#   choose to re-encode.
#
#   Use this beta version of the script when making code changes. Do not 
#   move the code changes to the Production version of the script until
#   the edited code has been thouroly tested.
#
#----------------------------------------------------------------------

#command to run this script: /home/jason/git_repositories/HandBrake_Scripts/HB_DashCam_Converter_Clone_Permissions_Worker_via_cp.sh

#------------------Original code using chmod command
#echo
#echo Starting to clone permissions from "$1" to "${1%\.*}".mp4
#chmod --reference="$1" "${1%\.*}".mp4
#echo Finished cloning permissions from "$1" to "${1%\.*}".mp4 with exit code of "$?"
#echo
#--------------------------------------------------------------------

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!New code using cp command!!!!!!!!!!!!!!!!!!!!!!!
# I am going to try to capture all the file attributes from original files
# on the SD card including file creation date and time, file permissions, etc, and
# not just the file permissions as i currently do using the chmod command.  By
# using the copy command (cp) with the right options I should be able to copy
# over all the file attributes including date and time of the recording.  Right now
# I only know the day the file was created after all the processing has been completed.
# I have to guess what time the file is for, but if I can copy over the file creation
# date from the SD card I can rename the file with that creation time. But currently it
# looks like the file created time attribute and real time recorded is offset by about
# 6 hours. Not sure why.  The file attribute will be 04:07:16 but the time title at the 
# bottom of the video will say 10:04:14.
#----------------------!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!Update: I figured out the time difference.  I could kinda reason
# why the time was offset by 6 hours but I didn't know why there was an extra 3 minutes
# of offset.  Then duh, the video is 3 minutes long.  When comparing the difference in
# time from the time stamp of the end of the video and the file creation attribute they
# are exactly 6 hours offset.  
# Example:  The video timestamp at the end will be 10:07:16 and the file creation attribute
# will be 04:07:16.  Bingo.  When renaming the files using the date time file attribute

cp -p -r ./ /media/jason/Backup2/VidConvert/DashCams/newvids/2018-02-11


echo
echo Starting to clone permissions from "$1" to "${1%\.*}".mp4
chmod --reference="$1" "${1%\.*}".mp4
echo Finished cloning permissions from "$1" to "${1%\.*}".mp4 with exit code of "$?"
echo


#Original source -> find /path/to/dest/ -type f -print0 | xargs -O -I {} chmod --reference=/path/to/rfile.txt {}
#Sourced from here -> https://www.cyberciti.biz/faq/how-to-copy-permissions-from-one-file-to-another-on-linux/


